# campaignhub/models.py

from django.db import models
from django.conf import settings
from accounts.models import Organization
from integrations.models import Integration
import uuid
from django.core.validators import MinValueValidator, MaxValueValidator

# --- Main Campaign Model ---
class PostStatusChoices(models.TextChoices):
    DRAFT = 'DRAFT', 'Draft'
    SCHEDULED = 'SCHEDULED', 'Scheduled'


class Campaign(models.Model):
    class CampaignType(models.TextChoices):
        BLOG = 'BLOG', 'Blog'
        SOCIAL = 'SOCIAL', 'Social'

    class Status(models.TextChoices):
        DRAFT = 'DRAFT', 'Draft'
        QUEUED = 'QUEUED', 'Queued'
        ACTIVE = 'ACTIVE', 'Active'
        COMPLETED = 'COMPLETED', 'Completed'
        ARCHIVED = 'ARCHIVED', 'Archived'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name='campaignhub')
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='campaignhub')

    name = models.CharField(max_length=255)
    status = models.CharField(
        max_length=10, choices=Status.choices, default=Status.QUEUED)

    # ADD THIS FIELD to your model
    campaign_type = models.CharField(
        max_length=10, choices=CampaignType.choices, default=CampaignType.BLOG)
    post_creation_status = models.CharField(
        max_length=10,
        choices=PostStatusChoices.choices,
        default=PostStatusChoices.SCHEDULED,
        help_text="The initial status for posts generated by the agent for this campaign."
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} ({self.get_campaign_type_display()} - {self.organization.name})"

# --- Models for Wizard Steps ---


class PromptTemplate(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name='prompt_templates')
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)

    name = models.CharField(
        max_length=255, help_text="A unique name for this prompt template.")

    campaign_type = models.CharField(
        max_length=10,
        choices=Campaign.CampaignType.choices,
        default=Campaign.CampaignType.BLOG
    )

    system_prompt = models.TextField(blank=True, null=True)
    user_prompt = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('organization', 'name', 'campaign_type')
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.name} ({self.get_campaign_type_display()})"


class PromptSettings(models.Model):
    campaign = models.OneToOneField(
        Campaign, on_delete=models.CASCADE, related_name='prompt_settings')
    prompt_name = models.CharField(max_length=255, blank=True, default='')
    system_prompt = models.TextField(blank=True, null=True)
    user_prompt = models.TextField(blank=True, null=True)


class Keyword(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)

    class Meta:
        unique_together = ('organization', 'text')

    def __str__(self):
        return self.text


class KeywordSettings(models.Model):
    campaign = models.OneToOneField(
        Campaign, on_delete=models.CASCADE, related_name='keyword_settings')
    keywords = models.ManyToManyField(Keyword, blank=True)
    use_clustering = models.BooleanField(default=False)


class ContentSettings(models.Model):
    class Tone(models.TextChoices):
        PROFESSIONAL = 'professional', 'Professional'
        FRIENDLY = 'friendly', 'Friendly'
        INFORMATIVE = 'informative', 'Informative'
        PERSUASIVE = 'persuasive', 'Persuasive'
        CASUAL = 'casual', 'Casual'
        PLAYFUL = 'playful', 'Playful'
        ASSERTIVE = 'assertive', 'Assertive'
        EMPATHETIC = 'empathetic', 'Empathetic'
        FORMAL = 'formal', 'Formal'
        CREATIVE = 'creative', 'Creative'
        HUMOROUS = 'humorous', 'Humorous'
        NEUTRAL = 'neutral', 'Neutral / Objective'

    campaign = models.OneToOneField(
        Campaign, on_delete=models.CASCADE, related_name='content_settings')
    word_count = models.PositiveIntegerField(default=1000)
    tone_of_voice = models.CharField(
        max_length=20, choices=Tone.choices, default=Tone.PROFESSIONAL)
    temperature = models.FloatField(default=1.0)
    tags = models.JSONField(
        null=True, blank=True, help_text="Stores tag settings: mode, count/list, include, etc."
    )
    categories = models.TextField(
        blank=True, help_text="Comma-separated categories")
    seo_plugin = models.CharField(max_length=50, blank=True)

    # AI Image settings (already exists, just ensure choices are consistent)
    ai_image_enabled = models.BooleanField(default=False)
    # In models.py, ensure styles match:
    ai_image_style = models.CharField(
        max_length=50, 
        blank=True, 
        choices=[
            ('realistic', 'Realistic'),
            ('artistic', 'Artistic'),
            ('minimal', 'Minimal'),
            ('vibrant', 'Vibrant'),
            ('professional', 'Professional'),
            ('photographic', 'Photographic'),
            ('digital_art', 'Digital Art'),
            ('fantasy', 'Fantasy')
        ],
        default='realistic'
    )
    ai_image_instructions = models.TextField(blank=True)

class MediaSettings(models.Model):
    class MediaType(models.TextChoices):
        IMAGE = 'image', 'image'
        VIDEO = 'video', 'video'

    class Source(models.TextChoices):
        AUTO = 'AUTO', 'Auto Search'
        MANUAL = 'MANUAL', 'Manually Add'

    campaign = models.OneToOneField(
        Campaign, on_delete=models.CASCADE, related_name='media_settings')
    media_type = models.CharField(
        max_length=10,
        choices=MediaType.choices,
        default=MediaType.IMAGE,
    )
    source_type = models.CharField(
        max_length=10, choices=Source.choices, default=Source.AUTO)
    image_source_platform = models.CharField(
        max_length=50, blank=True, null=True)
    search_prompt = models.TextField(blank=True, null=True)
    # Store the URL for the main cover image
    cover_images = models.JSONField(default=dict, blank=True)
    # Store a list of URLs for images to be used in the content
    content_images = models.JSONField(default=list, blank=True)


class ScheduleSettings(models.Model):
    class Frequency(models.TextChoices):
        MINUTES = 'MINUTES', 'Minutes'
        HOURS = 'HOURS', 'Hours'
        DAYS = 'DAYS', 'Days'
        WEEKS = 'WEEKS', 'Weeks'
        MONTHS = 'MONTHS', 'Months'

    class EndCondition(models.TextChoices):
        NEVER = 'NEVER', 'Never'
        AFTER = 'AFTER', 'After N Runs'
        UNTIL = 'UNTIL', 'Until Date'

    end_condition_type = models.CharField(
        max_length=10,
        choices=EndCondition.choices,
        default=EndCondition.NEVER
    )
    # Stores the 'N' for 'After N Runs'
    end_condition_runs = models.PositiveIntegerField(null=True, blank=True)
    # Stores the date for 'Until Date'
    end_condition_date = models.DateTimeField(null=True, blank=True)

    campaign = models.OneToOneField(
        Campaign, on_delete=models.CASCADE, related_name='schedule_settings')
    start_datetime = models.DateTimeField()
    frequency_unit = models.CharField(max_length=10, choices=Frequency.choices)
    frequency_value = models.PositiveIntegerField(default=1)
    timezone = models.CharField(max_length=100, default='UTC')


    # Add these new fields for randomness
    randomness_percent = models.PositiveIntegerField(
        default=0,
        validators=[MinValueValidator(0), MaxValueValidator(100)],  
        help_text="Randomness percentage (0-100)")
    
    randomness_lock = models.BooleanField(
        default=False,
        help_text="If True, randomness is disabled and exact times are used")


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DRAFT', 'Draft'
        SCHEDULED = 'SCHEDULED', 'Scheduled'
        PUBLISHED = 'PUBLISHED', 'Published'
        GENERATION_FAILED = 'FAILED', 'Generation Failed'
        PUBLISH_FAILED = 'PUBLISH_FAILED', 'Publish Failed' 

    campaign = models.ForeignKey(
        Campaign, on_delete=models.CASCADE, related_name='posts')
    keyword = models.ForeignKey(
        Keyword, on_delete=models.SET_NULL, null=True, blank=True)
    integration_target = models.ForeignKey(
        Integration, on_delete=models.SET_NULL, null=True)
    meta_description = models.TextField(blank=True, null=True)
    tags = models.JSONField(default=list, blank=True,
                            help_text="List of tags for the post.")
    categories = models.JSONField(
        default=list, blank=True, help_text="List of category IDs for the post.")

    title = models.CharField(max_length=255)
    content = models.TextField()
    status = models.CharField(
        max_length=20, choices=Status.choices, default=Status.DRAFT)

    publish_at = models.DateTimeField()
    published_url = models.URLField(blank=True, null=True)
    error_message = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    featured_image_url = models.URLField(blank=True, null=True, help_text="Original image URL from media settings")
    wordpress_media_id = models.IntegerField(blank=True, null=True, help_text="WordPress media library ID after upload")
    wordpress_image_url = models.URLField(blank=True, null=True, help_text="WordPress media library URL")

    @property
    def is_failed(self):
        """Returns True if the post is in any failed state."""
        return self.status in [self.Status.GENERATION_FAILED, self.Status.PUBLISH_FAILED]

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title




class CampaignLog(models.Model):
    """Stores a log entry related to a specific campaign run."""
    class LogLevel(models.TextChoices):
        INFO = 'INFO', 'Info'
        WARNING = 'WARNING', 'Warning'
        ERROR = 'ERROR', 'Error'
        DEBUG = 'DEBUG', 'Debug'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    campaign = models.ForeignKey(
        Campaign, on_delete=models.CASCADE, related_name='logs')
    post = models.ForeignKey(
        Post, on_delete=models.SET_NULL, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    level = models.CharField(
        max_length=10, choices=LogLevel.choices, default=LogLevel.INFO)
    node_name = models.CharField(max_length=100, blank=True)
    message = models.TextField()

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"[{self.created_at.strftime('%Y-%m-%d %H:%M')}] [{self.level}] {self.message[:80]}"
