# Generated by Django 5.2.7 on 2025-10-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer'), ('CUSTOMADMIN', 'Custom Admin')], default='VIEWER', max_length=20),
        ),
    ]
