# Generated by Django 5.2.7 on 2025-11-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_invitation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DECLINED', 'Declined')], default='PENDING', max_length=10),
        ),
    ]
