# Generated by Django 5.2.6 on 2025-10-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_organization_organizationmember_organization_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="two_factor_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="two_factor_code_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
