# Generated by Django 5.2.6 on 2025-10-03 10:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_two_factor_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="webhook_url",
        ),
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("webhook_url", models.URLField(blank=True, null=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="accounts.organization",
                    ),
                ),
            ],
        ),
    ]
