# Generated by Django 5.2.6 on 2025-10-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_profile_api_key_remove_profile_webhook_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationsettings",
            name="billing_is_yearly",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="subscription_plan",
            field=models.CharField(default="free", max_length=20),
        ),
    ]
