# Generated by Django 5.2.7 on 2025-10-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organizationsettings_billing_is_yearly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='stripe_subscription_cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
