# Generated by Django 5.2.7 on 2025-11-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_organizationmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
