# Generated by Django 5.2.7 on 2025-11-07 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_organizationsettings_subscription_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('output_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of outputs allowed. Null means unlimited.', null=True)),
                ('campaign_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of campaigns allowed. Null means unlimited.', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='accounts.plan'),
        ),
    ]
