# Generated by Django 5.2.7 on 2025-11-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_plan_organizationsettings_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='credit_grant',
            field=models.PositiveIntegerField(default=1, help_text='The number of output credits granted when subscribing to this plan.'),
        ),
    ]
