# Generated by Django 5.2.7 on 2025-11-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_plan_credit_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='output_credits_remaining',
            field=models.PositiveIntegerField(default=0, help_text='The number of post/output credits the organization has left.'),
        ),
    ]
