# Generated by Django 5.2.7 on 2025-11-08 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_organizationsettings_output_credits_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationsettings',
            name='subscription_plan',
        ),
    ]
