# Generated by Django 5.2.7 on 2025-11-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_organizationsettings_subscription_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationsettings',
            old_name='plan',
            new_name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='billing_is_yearly',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_plan',
        ),
    ]
