# Generated by Django 5.2.7 on 2025-11-08 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_plan_organizationsettings_subscription_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='output_limit',
        ),
    ]
