# Generated by Django 5.2.7 on 2025-11-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_plan_output_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='campaigns_created_this_period',
            field=models.PositiveIntegerField(default=0, help_text='Tracks how many active campaigns have been created in the current billing cycle.'),
        ),
    ]
