# Generated by Django 5.2.7 on 2025-11-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customuser_managers_customuser_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delete_confirmation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='delete_confirmation_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
