# Generated by Django 5.2.7 on 2025-11-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_profile_delete_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsettings',
            name='output_credits_remaining',
            field=models.PositiveIntegerField(default=1, help_text='The number of post/output credits the organization has left.'),
        ),
    ]
