# Generated by Django 5.2.6 on 2025-10-03 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_organizationsettings_billing_is_yearly_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("WORDPRESS", "WordPress"),
                            ("MEDIUM", "Medium"),
                            ("GHOST", "Ghost"),
                            ("NOTION", "Notion"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        help_text="The base URL of the WordPress site (e.g., https://example.com)",
                        max_length=255,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=150, null=True)),
                ("api_key", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("last_tested", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "provider")},
            },
        ),
    ]
