# Generated by Django 5.2.6 on 2025-10-03 19:03

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="api_key",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
