# Generated by Django 5.2.7 on 2025-10-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_integration_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('WORDPRESS', 'WordPress'), ('MEDIUM', 'Medium'), ('GHOST', 'Ghost'), ('NOTION', 'Notion'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('X', 'X (Formerly Twitter)'), ('LINKEDIN', 'LinkedIn'), ('THREADS', 'Threads')], max_length=20),
        ),
    ]
