# Generated by Django 5.2.6 on 2025-10-13 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_organizationsettings_billing_is_yearly_and_more"),
        ("integrations", "0002_alter_integration_api_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("QUEUED", "Queued"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[("BLOG", "Blog"), ("SOCIAL", "Social")],
                        default="BLOG",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaignhub",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaignhub",
                        to="accounts.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word_count", models.PositiveIntegerField(default=1000)),
                (
                    "tone_of_voice",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("friendly", "Friendly"),
                            ("informative", "Informative"),
                            ("persuasive", "Persuasive"),
                            ("casual", "Casual"),
                            ("playful", "Playful"),
                            ("assertive", "Assertive"),
                            ("empathetic", "Empathetic"),
                            ("formal", "Formal"),
                            ("creative", "Creative"),
                            ("humorous", "Humorous"),
                            ("neutral", "Neutral / Objective"),
                        ],
                        default="professional",
                        max_length=20,
                    ),
                ),
                ("temperature", models.FloatField(default=1.0)),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        help_text="Stores tag settings: mode, count/list, include, etc.",
                        null=True,
                    ),
                ),
                (
                    "categories",
                    models.TextField(
                        blank=True, help_text="Comma-separated categories"
                    ),
                ),
                ("seo_plugin", models.CharField(blank=True, max_length=50)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_settings",
                        to="campaignhub.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "text")},
            },
        ),
        migrations.CreateModel(
            name="KeywordSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("use_clustering", models.BooleanField(default=False)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyword_settings",
                        to="campaignhub.campaign",
                    ),
                ),
                (
                    "keywords",
                    models.ManyToManyField(blank=True, to="campaignhub.keyword"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MediaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("AUTO", "Auto Search"), ("MANUAL", "Manually Add")],
                        default="AUTO",
                        max_length=10,
                    ),
                ),
                (
                    "image_source_platform",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("search_prompt", models.TextField(blank=True, null=True)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_settings",
                        to="campaignhub.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SCHEDULED", "Scheduled"),
                            ("PUBLISHED", "Published"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("publish_at", models.DateTimeField()),
                ("published_url", models.URLField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="campaignhub.campaign",
                    ),
                ),
                (
                    "integration_target",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="integrations.integration",
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campaignhub.keyword",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("system_prompt", models.TextField(blank=True, null=True)),
                ("user_prompt", models.TextField(blank=True, null=True)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_settings",
                        to="campaignhub.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                (
                    "frequency_unit",
                    models.CharField(
                        choices=[
                            ("MINUTES", "Minutes"),
                            ("HOURS", "Hours"),
                            ("DAYS", "Days"),
                            ("WEEKS", "Weeks"),
                            ("MONTHS", "Months"),
                        ],
                        max_length=10,
                    ),
                ),
                ("frequency_value", models.PositiveIntegerField(default=1)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_settings",
                        to="campaignhub.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A unique name for this prompt template.",
                        max_length=255,
                    ),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[("BLOG", "Blog"), ("SOCIAL", "Social")],
                        default="BLOG",
                        max_length=10,
                    ),
                ),
                ("system_prompt", models.TextField(blank=True, null=True)),
                ("user_prompt", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompt_templates",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("organization", "name", "campaign_type")},
            },
        ),
    ]
