# Generated by Django 5.2.6 on 2025-10-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaignhub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediasettings",
            name="content_images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="mediasettings",
            name="cover_image",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
