# Generated by Django 5.2.7 on 2025-10-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignhub', '0002_mediasettings_content_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesettings',
            name='end_condition_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulesettings',
            name='end_condition_runs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulesettings',
            name='end_condition_type',
            field=models.CharField(choices=[('NEVER', 'Never'), ('AFTER', 'After N Runs'), ('UNTIL', 'Until Date')], default='NEVER', max_length=10),
        ),
    ]
