# Generated by Django 5.2.7 on 2025-10-15 10:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignhub', '0003_schedulesettings_end_condition_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug')], default='INFO', max_length=10)),
                ('node_name', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='campaignhub.campaign')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaignhub.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
