# Generated by Django 5.2.7 on 2025-10-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignhub', '0005_alter_campaign_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediasettings',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='mediasettings',
            name='cover_images',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
