# Generated by Django 5.2.7 on 2025-10-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignhub', '0006_remove_mediasettings_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='List of category IDs for the post.'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tags for the post.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('FAILED', 'Generation Failed')], default='DRAFT', max_length=10),
        ),
    ]
