# Generated by Django 5.2.7 on 2025-11-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignhub', '0008_alter_post_options_post_created_at_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesettings',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
