# Generated by Django 5.2.7 on 2025-11-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignhub', '0009_schedulesettings_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlog',
            name='post_creation_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled')], default='SCHEDULED', help_text='The initial status for posts generated by the agent for this campaign.', max_length=10),
        ),
    ]
