# Generated by Django 5.2.7 on 2025-11-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignhub', '0011_remove_campaignlog_post_creation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('FAILED', 'Generation Failed'), ('PUBLISH_FAILED', 'Publish Failed')], default='DRAFT', max_length=20),
        ),
    ]
