# Generated by Django 5.2.7 on 2025-11-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaignhub', '0012_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='Original image URL from media settings', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='wordpress_image_url',
            field=models.URLField(blank=True, help_text='WordPress media library URL', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='wordpress_media_id',
            field=models.IntegerField(blank=True, help_text='WordPress media library ID after upload', null=True),
        ),
    ]
