# Generated by Django 5.2.7 on 2025-11-20 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaignhub",
            "0013_post_featured_image_url_post_wordpress_image_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulesettings",
            name="randomness_lock",
            field=models.BooleanField(
                default=False,
                help_text="If True, randomness is disabled and exact times are used",
            ),
        ),
        migrations.AddField(
            model_name="schedulesettings",
            name="randomness_percent",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Randomness percentage (0-100)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
