# Generated by Django 5.2.7 on 2025-11-25 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaignhub", "0015_mediasettings_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentsettings",
            name="ai_image_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contentsettings",
            name="ai_image_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contentsettings",
            name="ai_image_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("realistic", "Realistic"),
                    ("artistic", "Artistic"),
                    ("minimal", "Minimal"),
                    ("vibrant", "Vibrant"),
                    ("professional", "Professional"),
                    ("photographic", "Photographic"),
                    ("digital_art", "Digital Art"),
                    ("fantasy", "Fantasy"),
                ],
                default="realistic",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="schedulesettings",
            name="randomness_percent",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Randomness percentage (0-100)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
